# Generated by Django 6.0.4 on 2026-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
