# Generated by Django 6.0.4 on 2026-04-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='max_members',
            field=models.IntegerField(default=50),
        ),
    ]
